'use strict'

var AddSVGLayerTests = require("./SVGLayerTests.js")
var AddSVGLayerSetTests = require("./SVGLayerSetTests.js")
var AddUMLWebWidgetErrorTests = require("./UMLWebWidgetErrorTests.js")
var AddSettingsTests = require("./SettingsTests.js")
var AddStyleTests = require("./StyleTests.js")
var AddConnectionPointPositionTests = require("./ConnectionPointPositionTests.js")
var AddConnectionPointTests = require("./ConnectionPointTests.js")
var AddConnectorTests = require("./ConnectorTests.js")
var AddLayoutManagerTests = require("./LayoutManagerTests.js")
var AddClassBoxTests = require("./ClassBoxTests.js")
var AddLifelineTests = require("./LifelineTests.js")
var AddActorTests = require("./ActorTests.js")
var AddUseCaseTests = require("./UseCaseTests.js")
var AddComponentTests = require("./ComponentTests.js")
var AddNodeTests = require("./NodeTests.js")
var AddClassDiagramTests = require("./ClassDiagramTests.js")
var AddSequenceDiagramTests = require("./SequenceDiagramTests.js")
var AddUseCaseDiagramTests = require("./UseCaseDiagramTests.js")
var AddComponentDiagramTests = require("./ComponentDiagramTests.js")
var AddDeploymentDiagramTests = require("./DeploymentDiagramTests.js")
var TestUtils = require("./TestUtils.js")
var tf = require("ishiko-test-framework")

let theTestHarness = new tf.TestHarness("codesmithy-umlwebwidget")

TestUtils.createDirectory(__dirname + "/output")

AddSVGLayerTests(theTestHarness)
AddSVGLayerSetTests(theTestHarness)
AddUMLWebWidgetErrorTests(theTestHarness)
AddSettingsTests(theTestHarness)
AddStyleTests(theTestHarness)
AddConnectionPointPositionTests(theTestHarness)
AddConnectionPointTests(theTestHarness)
AddConnectorTests(theTestHarness)
AddLayoutManagerTests(theTestHarness)
AddClassBoxTests(theTestHarness)
AddLifelineTests(theTestHarness)
AddActorTests(theTestHarness)
AddUseCaseTests(theTestHarness)
AddComponentTests(theTestHarness)
AddNodeTests(theTestHarness)
AddClassDiagramTests(theTestHarness)
AddSequenceDiagramTests(theTestHarness)
AddUseCaseDiagramTests(theTestHarness)
AddComponentDiagramTests(theTestHarness)
AddDeploymentDiagramTests(theTestHarness)

theTestHarness.run()
